# ============================================
# Nombre de la aplicación
# ============================================
spring.application.name=rollerspeed

# ============================================
# Configuración de Base de Datos MySQL
# ============================================
spring.datasource.url=jdbc:mysql://localhost:6033/rollerspeed_db?serverTimezone=UTC&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=RItual12345
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ============================================
# Configuración de JPA / Hibernate
# ============================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ============================================
# Configuración de Thymeleaf
# ============================================
spring.thymeleaf.cache=false

# ============================================
# Puerto del servidor
# ============================================
server.port=8080